/**
 * Tripoley app types — re-exported from @playfield/core so UI and engine cannot drift apart.
 * Add UI-only types here if needed; do not duplicate GameState / GameAction.
 */
export type {
  Suit,
  Rank,
  Card,
  HouseRules,
  HouseRulesPreset,
  PokerHandRank,
  SuddenDeathReason,
  SuddenDeathState,
  AIDifficulty,
  Player,
  GamePhase,
  PotSectionKey,
  PotBoard,
  MichiganState,
  PokerState,
  BlindAuctionState,
  PayCardClaim,
  PhaseAnnouncement,
  AnnouncementContinue,
  GameLogEntry,
  GameState,
  AnimationKind,
  AnimationAnchor,
  AnimationType,
  SeatConfig,
  PokerAction,
  GameAction,
  SectionLabel,
  PotSection,
  FeedbackType,
} from '@playfield/core';
